services:
  registry:
    image: "registry:3"
    container_name: "registry"
    restart: always
    ports:
      # so, somebody did THIS mapping:
      # 4321:80
      # if it worked it would mean that GITLAB_OMNIBUS_CONFIG failed to configure nginx
      # and it's listening on default 80 port, not cool
      # so I'm mapping for 4321 container port to check if config is working correctly
      - 5000:5000
