name: "mailpit"
services:
  mailpit:
    image: axllent/mailpit:v1.27
    container_name: mailpit
    environment:
      - MP_DATABASE=/data/mailpit.db
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
      - MP_UI_AUTH=user:user
    volumes:
      - "./data:/data"
    ports:
      - "1025:1025"
      - "8025:8025"